---
- hosts: '{{env}}'
  become: yes
  tasks:
    - name: Check and remove existing containers
      shell: |
        if [ `docker ps -a | wc -l` -gt 1 ]; then
          echo "Service found"
          docker rm -f $(docker ps -aq)
          docker system prune -fa
          docker service rm `docker service ls | grep -v NAME | grep mysvc | awk '{print $2}'`
        else
          echo "No Service found"
        fi
    - name: Deploy phpapp
      command: docker service create --name mysvc --replicas 2 -p 9080:8080 mahathkrish/phpapp:'{{build}}'
